### ISSUE TITLE
Suggestion: let Jellyscrub plugin handles file manipulation instead

### ISSUE THREAD

**Issue by bennydiamond** [kdkasad/docker-mod-jellyfin-jellyscrub#2]
As the title suggests, wouldn't it be more future proof to simply have a script change the files permissions Jellyscrub will normally attempt to change?

From what I understand, you seem to manually patch web server's file rather than letting the add-on handle it. If you change file permission or ownership, it gives write access to the plugin. If the plugin ever changes behavior, you will not have to update this docker mod unless it requires rewriting more files.

**Comment by kdkasad** [comment]
I do like that idea, although I've stopped working on this project since it does what I need. It was more of a quick solution that I published only to help others who need it. If you'd like to open a PR with the changes, I'll gladly merge it. Otherwise I'll probably only change this mod if it stops working properly.
